### ISSUE TITLE
Fetching SSID needs updating

### ISSUE THREAD

**Issue by Alitejawi** [PezzaD84/Device-Information#1]
Across multiple computers I have tested the app, it works fine except for the command to grab the SSID connected to. Below is (one of) the ways to get this working. 

`networkname=$(/usr/sbin/networksetup -listallhardwareports | /usr/bin/awk '/Wi-Fi/{getline; print $2}' | /usr/bin/xargs networksetup -getairportnetwork | /usr/bin/awk -F ' ' '{print $NF}')`

**Comment by PezzaD84** [comment]
Hi @Alitejawi 

Thank you very much for the updated code. I hadn't even noticed it had stopped working so thank you!
Just updated the script to include this.

Cheers 🍻
